### ISSUE TITLE
hemingway panicking at missing update-field in feed

### ISSUE THREAD

**Issue by mborejdo** [jahzielv/hemingway#2]
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\xxx\.tools\registry\src\github.com-1ecc6299db9ec823\hemingway-0.5.1\src/main.rs:170:40`

The feeds I am trying to consume are usually atom or rss feeds. They do not contain an update-field, which seems to be expected.

**Comment by jahzielv** [comment]
Hey @mborejdo! Thanks for checking out Hemingway!

I've gotten that same error a couple times with different feeds that I've added and was actually planning on tackling it this week (along with some other improvements). I'll do some thinking about how to handle feeds without an update field with [the crate I'm using for feed processing](https://docs.rs/feed-rs/0.3.0/feed_rs/). PRs are also welcome if you have any ideas for how to patch the bug!

**Comment by mborejdo** [comment]
Hey @jahzielv  thanks for writing hemingway, one of the missing parts in my cross-OS (rust) cli experience :-). Hopefully you will keep windows functionality :-)
Unfortunately I cannot provide a PR, as I am just trying to learn Rust (I have many Ideas, just missing skills :-/). I am not sure if  the pubDate or lastBuildDate could be used as some fallback mechanism if the update field is missing

**Comment by jahzielv** [comment]
@mborejdo I just published 0.6.0, which should fix this bug! Let me know if it works for you. Thanks again for opening this issue, and please feel free to open more if you find bugs or just have suggestions! 😄

**Comment by mborejdo** [comment]
hey @jahzielv . I can confirm 0.6.0 does fix the panic and now works as expected for my feeds. Unfortunately the update also changed some layout. I liked the compact rendering more, but will open an approptiate issue for that topic.
